apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  type: NodePort  # Change to LoadBalancer if on cloud or ClusterIP for internal
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30000  # NodePort range is 30000-32767
  selector:
    app: sonarqube
